adding github actions for linting
iron-fish/ironfish-frost pull request #26
Opened 2024-02-29 21:37 UTC by patnir

2024-02-29 22:01 UTC, patnir commented on .github/workflows/ci.yml
> +          cargo test
went with cargo test instead of tarpaulin because i figured in the short-medium term we don't need to report coverage

2024-03-01 01:43 UTC, andiflabs requested changes

2024-03-01 01:43 UTC, andiflabs commented on .github/workflows/ci.yml
> +          cargo check --locked --all-targets
This is a lib crate: the Cargo.lock is ignored by consumers

2024-03-01 01:43 UTC, andiflabs commented on .gitignore
> -/Cargo.lock
This remain ignored

2024-03-01 01:43 UTC, andiflabs commented on ci/lintHeaders.sh
> +files=$(find $1 -type f -name '*.rs')
Use an array to avoid unwanted expansion later on:

```bash
files=( src/**/*.rs )
```

or:


```bash
files=( **/*.rs )
```

2024-03-01 01:43 UTC, andiflabs commented on ci/lintHeaders.sh
> +for file in $files; do
If you make `files` an array, then replace `$files` with `"${files[@]}"` to prevent expansion

2024-03-01 01:43 UTC, andiflabs commented on ci/lintHeaders.sh
> +3'
I guess this works but perhaps an easier way to achieve the same result would be:

```bash
license="/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */"
[[ "$(head -n3 "$1")" = "$license" ]]
```

2024-03-01 01:43 UTC, andiflabs commented on .github/workflows/ci.yml
> +          rustup component add rustfmt clippy
Nit: these tools are not needed for tests

2024-03-01 02:55 UTC, closed without merging